apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: avaf-system
  description: Sample AVAF team
spec:
  owner: avaf-sample-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: avaf-system
  description: The avaf team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-ui
  description: Online ui description test
spec:
  type: website
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  # dependsOn:
  #   - kafka
  consumesApis:
    - online-bff-api
    - e-contract-bff-api
    - reference-data-api
    - deal-management-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e-contract-ui
  description: e contract ui description test
spec:
  type: website
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  # dependsOn:
  #   - kafka
  consumesApis:
    - online-bff-api
    - e-contract-bff-api
    - reference-data-api
    - deal-management-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deal-management-ui
  description: deal management ui description test
spec:
  type: website
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  # dependsOn:
  #   - kafka
  consumesApis:
    - online-bff-api
    - e-contract-bff-api
    - reference-data-api
    - deal-management-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-bff
  description: online bff test
spec:
  type: service
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  providesApi: online-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: online-bff-api
  description: online bff test
spec:
  type: openapi
  lifecycle: production
  owner: avaf-sample-team
  system: avaf-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Sample API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /sample:
        get:
          summary: List all samples

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e-contract-bff
  description: e contract bff test
spec:
  type: service
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  providesApi: e-contract-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: e-contract-bff-api
  description: e contract bff test
spec:
  type: openapi
  lifecycle: production
  owner: avaf-sample-team
  system: avaf-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Sample API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /sample:
        get:
          summary: List all samples

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reference-data
  description: reference data test
spec:
  type: service
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  providesApi: reference-data-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reference-data-api
  description: reference data test
spec:
  type: openapi
  lifecycle: production
  owner: avaf-sample-team
  system: avaf-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Sample API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /sample:
        get:
          summary: List all samples

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deal-management-bff
  description: deal management bff test
spec:
  type: service
  lifecycle: production
  owner: avaf-sample-team
  partOf: avaf-system
  providesApi: deal-management-bff-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: deal-management-bff-api
  description: deal management bff test
spec:
  type: openapi
  lifecycle: production
  owner: avaf-sample-team
  system: avaf-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Sample API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /sample:
        get:
          summary: List all samples

---
# apiVersion: backstage.io/v1alpha1
# kind: Resource
# metadata:
#   name: kafka
#   description: Kafka description
# spec:
#   type: service
#   owner: avaf-sample-team
#   partOf: avaf-system
  # dependencyOf:
  #   - online-ui
  #   - e-contract-ui
  #   - deal-management-ui
